# Orb 'cypress-io/cypress@1' resolved to 'cypress-io/cypress@1.27.0'
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.16-browsers
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}-{{ checksum "app/yarn.lock"}}

      - run: cp .env.example .env
      - run: yarn install
      - run: cd app && yarn install && cd ../
      - run: yarn audit
      - run: cd app && yarn audit && cd ../

      - save_cache:
          paths:
            - node_modules
            - app/node_modules
            - ../.cache/Cypress
          key: dependencies-{{ checksum "yarn.lock" }}-{{ checksum "app/yarn.lock"}}

      # run tests!
      - run: yarn eslint
      - run: yarn test-chrome-headless
      - run:
          name: Build the app so that server can be started
          command: cd app && yarn build && cd ../
      - run:
          name: Start server with correct env for cypress tests
          command: >
            yarn generate-cert && ADALITE_ENABLE_HTTPS=true
            ADALITE_SERVER_URL='https://localhost:3000' PORT=3000
            ADALITE_BLOCKCHAIN_EXPLORER_URL='https://explorer-testnet.adalite.io'
            ADALITE_NETWORK='MARY_TESTNET' ADALITE_ENABLE_SERVER_MOCKING_MODE=true
            ADALITE_MOCK_TX_SUBMISSION_SUCCESS=true ADALITE_MOCK_TX_SUMMARY_SUCCESS=true
            yarn start-server
          wait-on: https://localhost:3000
          background: true
      - run:
          name: Run Cypress tests
          store_artifacts: true
          command: yarn cypress:run
      - store_artifacts:
          path: app/cypress/videos
      - store_artifacts:
          path: app/cypress/screenshots

workflows:
  version: 2
  workflow:
    jobs:
      - build
